name: Build Arch ISO

on:
  push:
    branches:
      - main

jobs:
  build-iso:
    runs-on: ubuntu-latest

    container:
      image: archlinux:latest
      options: --privileged

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Initialize pacman keyring
        run: |
          pacman-key --init
          pacman-key --populate archlinux

      - name: Update system and install archiso
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm archiso git squashfs-tools

      - name: Build ISO
        run: |
          mkarchiso -vrw ./work -o . .

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: "ISO"
          path: ./*.iso

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.date.outputs.date }}
          name: SebOS ${{ steps.date.outputs.date }}
          files: ./*.iso
          generate_release_notes: true
